# _config.yml
title: "RedstoneMaster01 Development"
description: "Development Website"
url: "https://github.com/RedstoneMaster011"
baseurl: ""


theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache


markdown: kramdown
highlighter: rouge
future: true
strict_front_matter: true
show_excerpts: true

header_pages:
  - index.md
  - projects.md
  - blog.md
  - contact.md


social:
  github: RedstoneMaster011
  email: redstonemaster109lukas@gmail.com
  youtube: RedstoneMaster01


redstone_mode: true
arduino_projects: true
matrix_control: true
minecraft_modding: true
node_exporter: true


seo:
  name: "RedstoneMaster01"
  type: "Person"
  github: "https://github.com/RedstoneMaster011"
  description: "I Code / Build Stuff Here"


exclude:
  - README.md
  - node_modules
  - vendor


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "RedstoneMaster01"
      comments: true
